// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOMHoCYeLmN-Vpg-ZhrRLTdO2vbAbZ5A8',
    appId: '1:764825575724:web:a7fe15f3c7c0ea8b528c89',
    messagingSenderId: '764825575724',
    projectId: 'linked-it',
    authDomain: 'linked-it.firebaseapp.com',
    storageBucket: 'linked-it.appspot.com',
    measurementId: 'G-JB22YF588K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKGlIXSAszLwLhk-PFMTPe1P1sdfQk0w4',
    appId: '1:764825575724:android:cd24eccf3e56fc8b528c89',
    messagingSenderId: '764825575724',
    projectId: 'linked-it',
    storageBucket: 'linked-it.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5CdBAFRgupu21hItWYBwarck0662B8fc',
    appId: '1:764825575724:ios:48b7187953ae808a528c89',
    messagingSenderId: '764825575724',
    projectId: 'linked-it',
    storageBucket: 'linked-it.appspot.com',
    iosClientId:
        '764825575724-ed9gqu2s91r3ta6aoc7punadr4v1jndk.apps.googleusercontent.com',
    iosBundleId: 'com.codex.aly.linkedit',
  );
}
